dna = "TCTGGTGCCACGCAAGCTCGAATACGAGGACCGGTAGGTCGAAAACGGAGATGTAGGACTACTAGCCTGCTAAGGTGCAGCAGAGCTTCTCCGGCTTAGTATAGAATTTAATGCAGTTGTTGCCAAAAACGGATCGTATCTGTTAGCTGCTATATCAGACGGCTCCAGCTACCGGACTATGTGCGACAGCTGACAGCGAATTTGGGTCGGTGAGGTCTACTGTCTTTGGAAGGACGGTCGTCTGCAGGATAGTGGTTCGGCACGGAACGGCGCTGGAATAAATAGATCCGGTAATTAGGCAGCGCTGTACTTTCTACACGTCAGTCGCGACACTGCTAGTCTACACGCTAGGTGTCCAATTCTGGAGGAGATTCTCTTTCGGTACGGTAGGTGACATAGGAAAATACGAATGGCAAATGAAGCTCCTACCCCCGAAGTGACAAGCCGCTGCCAACTTACGGGAACCGCGCACCATTTCTTACGTCAAGGTATGACAGTGCTGTCGTTCTGGAGCAGATAAAGCGACTCCATCAGGTACAGCCTCAGTCGTCCACCGGATTCTTTACGCACCACACAGGAGCTCATATTCCCTCCTGAAGAGAGAGTCTTGTGGGGGACTGTCAGGGCGCTCCTCATATGCCCGATATGTCGCGACCGGCCTCCCGTCAGGCTTCTTCGATGGTTTTCAACACGTCAGGGGATCGTAACCCACGGTCTTGGCGGCTAACAAAGACCGTCATGTAGCCACCACATGTTCATCCACGTCACTCTGGCATTAAATTTGAGGGTGATTGCACGCATGCTTGCAAAGCCAACGGCGTTTCGATATACCCTAGTGAAACAGACCGCTCGCATATTTAGCAGGTTGGTCGAATACGCCATTCACGTATAATGTTGGTCGTCCTATCAAGTATATAGTGTCCCCGGATTGATCCATATCACTAAGCGTGTGTCAGGAAAGACTGCTCGGATAGCTATCGAAAAAGAGCTAA".split('')
a = 0
c = 0
g = 0
t = 0
dna.each do |symbol|
	if symbol == "A"
		a = a + 1
	end
	if symbol == "C"
		c = c + 1
	end
	if symbol == "G"
		g = g + 1
	end
	if symbol == "T"
		t = t + 1
	end
end
puts a.inspect
puts c.inspect
puts g.inspect
puts t.inspect

